# Generated by Django 6.0.6 on 2026-06-10 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('website_clicks', models.PositiveIntegerField(default=0)),
                ('github_clicks', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_logs', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Project Analytics',
                'unique_together': {('project', 'date')},
            },
        ),
    ]
